#!/usr/bin/python3

from time import sleep
from urllib import request
from json import loads
from pathlib import Path

# https://darksky.net/dev/account
weather_api_key_path = f"{str(Path.home())}/weather.key"
with open(weather_api_key_path, 'r') as file:
    api_key = file.read().strip()

location = request.urlopen("https://ipinfo.io/loc", timeout=1).read().decode("utf-8").strip()
query = f"https://api.darksky.net/forecast/{api_key}/{location}?units=ca&exclude=minutely,hourly,daily,flags"
raw_weather_info = loads(request.urlopen(query).read())
current_weather_info = raw_weather_info["currently"]

temperature = f'{current_weather_info["temperature"]:3.1f}°C'
feels_like = f'{current_weather_info["apparentTemperature"]:3.1f}°C'

print(f"{temperature}/{feels_like}")
