#!/bin/fish
# vim:filetype=fish

pkill -9 -x polybar

set -x WIFI (ls /sys/class/net | grep wl)
set -x ETHERNET (ls /sys/class/net | grep en)

for m in (polybar --list-monitors | cut -d":" -f1)
  env MONITOR=$m polybar --reload top &
end
