#!/bin/fish
# vim:filetype=fish

set address unix:@kitty

if test -n "$argv"
  kitty @ --to=$address new-window --new-tab $argv
else
  if not pgrep -x kitty > /dev/null
    kitty --detach --single-instance --listen-on=$address
  end
end

