#!/usr/bin/bash

B='#00000000' # blank
C='#ffffff22' # clear ish
D='#282828ff' # default
T='#1d2021ff' # text
W='#880000ff' # wrong
V='#fb4934ff' # verifying

image=$(mktemp)
grim $image
convert $image -blur 5x4 $image
swaylock -e -f -i $image "$@" \
  --inside-ver-color $C \
  --ring-ver-color $V \
  --inside-wrong-color $C \
  --ring-wrong-color $W \
  --inside-color $B \
  --ring-color $D \
  --line-color $B \
  --separator-color $D \
  --text-ver-color $T \
  --text-wrong-color $T
rm -f $image
