#!/usr/bin/bash

if [ -z "$WAYLAND_DISPLAY" ]; then
  B='#00000000' # blank
  C='#ffffff22' # clear ish
  D='#282828ff' # default
  T='#1d2021ff' # text
  W='#880000ff' # wrong
  V='#fb4934ff' # verifying

  i3lock \
    --insidevercolor=$C \
    --ringvercolor=$V \
    --insidewrongcolor=$C \
    --ringwrongcolor=$W \
    --insidecolor=$B \
    --ringcolor=$D \
    --linecolor=$B \
    --separatorcolor=$D \
    --verifcolor=$T \
    --wrongcolor=$T \
    --timecolor=$T \
    --datecolor=$T \
    --layoutcolor=$T \
    --keyhlcolor=$W \
    --bshlcolor=$W \
    --screen \
    1 \
    --blur \
    3 \
    --clock \
    --indicator \
    --timestr="%H:%M:%S" \
    --datestr="%A, %m %Y" \
    --veriftext="hmmm..." \
    --wrongtext="lolnope"
else
  image=$(mktemp)
  grim $image
  convert $image -blur 0x1 $image
  swaylock -i $image "$@"
  rm -f $image
fi
