#!/usr/bin/bash

primary_monitor=$(xrandr | grep ' connected' | awk '/primary/ {print $1;}')
[ $HOSTNAME == "h500i" ] && primary_mode="--mode 1920x1080 --rate 144" || primary_mode="--auto"

[[ $HOSTNAME == "ideapad" ]] && secondary_monitor="DisplayPort-0" || secondary_monitor="$(xrandr | grep ' connected' | awk '/HDMI/ {print $1;}' | sed -n 1p)"
secondary_mode="--auto"

case "$@" in
"1")
  xrandr --output $secondary_monitor --off --output $primary_monitor $primary_mode
  ;;
"2")
  if [ "$secondary_monitor" ]; then
    xrandr --output $primary_monitor --off --output $secondary_monitor $secondary_mode
  else
    echo "No monitor connected"
  fi
  ;;
"all")
  if [ "$secondary_monitor" ]; then
    xrandr --output $primary_monitor $primary_mode --output $secondary_monitor $secondary_mode --right-of $primary_monitor
  else
    echo "No secondary monitor connected"
  fi
  ;;
"clone")
  xrandr --output $primary_monitor $primary_mode --output $secondary_monitor $secondary_mode --same-as $primary_monitor
  ;;
*)
  (xrandr --listactivemonitors | grep -q $secondary_monitor) && monitors 1 || monitors all
  ;;
esac
