#!/bin/fish
# vim:filetype=fish

# Dependencies:
# xclip
# imagemagick

set file (echo /tmp/(date +"%Y_%m_%d_%I_%M_%S_%p").png)

if test -n "$argv[1]"
  import $file
else
  import -window root $file
end

xclip -selection clipboard -t image/png -i $file 
