#!/usr/bin/bash

# Dependencies:
# redshift
# light

current_light=$(printf "%.0f\n" $(light -G))

if [ $current_light -lt 15 ] || [[ $1 = 0 ]]; then
	light -S 100
	redshift -x
else
	light -S 10
	redshift -O 2000
fi    
