#!/usr/bin/python3
# deps: wallutils

from glob import iglob
from os.path import isfile
from pathlib import Path
from random import choice
from subprocess import run
from time import sleep

wallpapers_path = f"{Path.home()}/Documents/Syncthing/WP/image"
wallpapers = [filename for filename in iglob(f"{wallpapers_path}/**/*", recursive=True) if
              isfile(filename)]

while True:
    if run(f"setwallpaper '{choice(wallpapers)}'", shell=True).returncode == 0:
        sleep(30)
    else:
        break
