#!/bin/bash

# http://github.com/mitchweaver/bin
# play a video on the root window

pkill -9 xwinwrap

xwin="xwinwrap -ni -b -fs -ov -nf --"

mpv="mpv --wid WID --no-config --keepaspect=no --shuffle --loop-playlist=inf \
    --no-border --vd-lavc-fast --x11-bypass-compositor=no \
    --gapless-audio=yes --vo=vdpau --hwdec=vdpau --really-quiet \
    --name=mpvbg"

$xwin $mpv "$1" &
