#!/usr/bin/python3

from time import sleep
from urllib import request
from json import loads
from pathlib import Path
from os import environ

# https://darksky.net/dev/account
api_key = environ['DARKSKY_API_KEY']

location = request.urlopen("https://ipinfo.io/loc", timeout=1).read().decode("utf-8").strip()
query = f"https://api.darksky.net/forecast/{api_key}/{location}?units=ca&exclude=minutely,hourly,daily,flags"
raw_weather_info = loads(request.urlopen(query).read())
current_weather_info = raw_weather_info["currently"]

temperature = f'{current_weather_info["temperature"]:3.1f}°C'
feels_like = f'{current_weather_info["apparentTemperature"]:3.1f}°C'

print(f"{temperature}/{feels_like}")
